// dictionary from shortform to longform occupation classes
var occ_dict = {
    "BUS": "Business Operation",
    "CLN": "Building and Grounds Cleaning and Maintenance",
    "CMM": "Computer and Mathematical Science",
    "CMS": "Community and Social Service",
    "CON": "Construction",
    "EAT": "Food Preparation and Serving Related",
    "EDU": "Educational Instruction and Library",
    "ENG": "Architecture and Engineering",
    "ENT": "Arts, Design, Entertainment, Sports, and Media",
    "EXT": "Extraction",
    "FFF": "Farming, Fishing, and Forestry",
    "FIN": "Financial Operation",
    "HLS": "Healthcare Support",
    "LGL": "Legal",
    "MED": "Healthcare Practitioners and Technical",
    "MGR": "Management",
    "MIL": "Military",
    "OFF": "Office and Administrative Support",
    "PRD": "Production",
    "PRS": "Personal Care and Service",
    "PRT": "Protective Service",
    "RPR": "Installation, Maintenance, and Repair",
    "SAL": "Sales and Related",
    "SCI": "Life, Physical, and Social Science",
    "TRN": "Transportation and Material Moving",
}